# -*- coding: utf-8 -*-

class ABD:    
    ALABAMA = ['AUBURN', 'BIRMINGHAM', 'DOTHAN', 'FLORENCE', 'GULF SHORES', 'HUNTSVILLE', 'MOBILE', 'MONTGOMERY', 'PETERSBURG', 'TROY', 'VALDEZ']
    
    ALASKA = ['ANCHORAGE', 'CORDOVA', 'JUNEAU', 'KODIAK', 'NAKNEK', 'SEWARD']
    
    ARIZONA = ['CHANDLER', 'GLENDALE', 'GRAND CANYON', 'MESA', 'PHOENIX', 'SCOTTSDALE', 'TEMPE', 'TUCSON']
    
    ARKANSAS = ['LITTLE ROCK']
    
    CALIFORNIA = ['ANAHEIM', 'BERKELEY', 'BURBANK', 'CHICO', 'CHULA VISTA', 'CONCORD', 'COSTA MESA', 'DALY CITY', 'DANVILLE', 'DAVIS', 'ESCONDIDO', 'FOLSOM', 'FREMONT', 'FRESNO', 'GOLETA', 'HUNTINGTON BEACH', 'INGLEWOOD', 'IRVINE', 'LANCASTER', 'LOMPOC', 'LONG BEACH', 'LOS ANGELES', 'MODESTO', 'MONTEREY', 'NORWALK', 'OAKLAND', 'OCEANSIDE', 'ONTARIO', 'OXNARD', 'PALM SPRINGS', 'PASADENA', 'RIVERSIDE', 'SACRAMENTO', 'SALINAS', 'SAN BERNARDINO', 'SAN DIEGO', 'SAN FRANCISCO', 'SAN JOSE', 'SANTA BARBARA', 'SANTA CLARA', 'SANTA CLARITA', 'SANTA MONICA', 'SIMI VALLEY', 'STOCKTON', 'THOUSAND OAKS', 'TORRANCE', 'TUSTIN', 'VALLEJO', 'WEST HOLLYWOOD']
    
    CARIBBEAN_DENIZI = ['ARUBA']
    
    COLORADO = ['BOULDER', 'COLORADO SPRINGS', 'DENVER', 'FORT COLLINS', 'SPRINGFIELD']
    
    CONNECTICUT = ['BRIDGEPORT', 'DANBURY', 'FAIRFIELD', 'HARTFORD', 'MILFORD', 'NEW HAVEN', 'STAMFORD', 'STRATFORD', 'VERNON', 'WATERBURY']
    
    DALY_CITY = ['WASHINGTON']
    
    DELAWARE = ['DOVER', 'FENWICK ISLAND', 'NEWARK', 'WILMINGTON']
    
    FLORIDA = ['BOCA RATON', 'BOYNTON BEACH', 'CLEARWATER', 'DAYTONA BEACH', 'DESTIN', 'FORT LAUDERDALE', 'GAINESVILLE', 'JACKSONVILLEE', 'MIAMI', 'OCALA', 'ORLANDO', 'PALM BEACH', 'PENSACOLA', 'SAINT PETERSBURG', 'SPRING HILL', 'TALLAHASSEE', 'TAMPA', 'TITUSVILLE', 'WINTER HAVEN']
    
    GEORGIA = ['ATLANTA', 'COLUMBUS', 'FORT BENNING', 'SAVANNAH', 'WARRENTON']
    
    HAVAI_ADALARI = ['HILO', 'HONOLULU']
    
    IDAHO = ['BOISE', 'MOSCOW', 'SUN VALLEY', 'TOLEDO', 'TWIN FALLS']
    
    ILLINOIS = ['CHAMPAIGN', 'CHICAGO', 'GALESBURG', 'URBANA']
    
    INDIANA = ['BLOOMINGTON', 'EVANSVILLE', 'FORT WAYNE', 'GARY', 'INDIANAPOLIS', 'LAFAYETTE', 'RICHMOND']
    
    IOWA = ['AMES', 'COUNCIL BLUFFS', 'DES MOINES', 'IOWA CITY', 'NEWTON']
    
    KANSAS = ['LAWRENCE', 'MANHATTAN', 'TOPEKA', 'WICHITA']
    
    KENTUCKY = ['BOWLING GREEN', 'FRANKFORT', 'LEXINGTON', 'LOUISVILLE']
    
    LOUISIANA = ['BATON ROUGE', 'NEW ORLEANS']
    
    MAINE = ['AUGUSTA', 'CAMDEN']
    
    MARYLAND = ['ANNAPOLIS', 'ARNOLD', 'BALTIMORE', 'BETHESDA', 'OCEAN CITY']
    
    MASSACHUSETTS = ['AMHERST', 'BOSTON', 'FALMOUTH', 'LYNN', 'WORCESTER']
    
    MICHIGAN = ['ANN ARBOR', 'BAY CITY', 'DETROIT', 'EAST LANSING', 'FLINT', 'GRAND RAPIDS', 'HOUGHTON', 'LANSING', 'MICHIGAN CENTER']
    
    MINNESOTA = ['BRAINERD', 'DULUTH', 'MINNEAPOLIS', 'ROCHESTER', 'SAINT PAUL']
    
    MISSISSIPPI = ['HATTIESBURG', 'JACKSON', 'OXFORD']
    
    MISSOURI = ['ANDERSON', 'COLUMBIA', 'COLUMBUS', 'JEFFERSON CITY', 'KANSAS CITY', 'MARYVILLE', 'ROLLA', 'SPRINGFIELD', 'ST. LOUIS']
    
    MONTANA = ['HELENA']
    
    NEBRASKA = ['LINCOLN', 'OMAHA']
    
    NEVADA = ['CARSON CITY', 'LAS VEGAS', 'RENO']
    
    NEW_HAMPSHIRE = ['EXETER', 'MANCHESTER']
    
    NEW_JERSEY = ['BLOOMFIELD', 'BURLINGTON', 'EANTONTOWN', 'NEW BRUNSWICK', 'NORTH PLAINFIELD', 'PATERSON', 'PISCATAWAY', 'PRINCETON', 'SALEM', 'SCOTCH PLAINS', 'SOMERSET', 'TRENTON', 'UNION CITY', 'WESTFIELD']
    
    NEW_MEXICO = ['ALBUQUERQUE', 'SANTA FE']
    
    NEW_YORK = ['ALBANY', 'BINGHAMTON', 'BROOKLYN (Cattaraugus)', 'BUFFALO', 'ELMIRA', 'GENEVA', 'ITHACA', 'NEW YORK', 'ROCHESTER', 'RONKONKOMA', 'SYRACUSE']
    
    NORTH_CAROLINA = ['BANNER ELK', 'CHARLOTTE', 'DURHAM', 'GREENSBORO', 'RALEIGH', 'RODANTHE', 'SHELBY']
    
    NORTH_DAKOTA = ['BISMARCK']
    
    OHIO = ['AKRON', 'CINCINNATI', 'CLEVELAND', 'COLUMBUS', 'DAYTON', 'KENT', 'YOUNGSTOWN']
    
    OKLAHOMA = ['LAWTON', 'OKLAHOMA CITY', 'STILLWATER', 'TULSA']
    
    OREGON = ['CORVALLIS', 'PORTLAND', 'SALEM', 'SISKIYOU']
    
    PENNSYLVANIA = ['ALLENTOWN', 'BETHLEHEN', 'ERIE', 'HARRISBURG', 'INDIANA', 'PHILADELPHIA', 'PITTSBURGH', 'STATE COLLEGE', 'TAMAQUA']
    
    RHODE_ISLAND = ['PROVIDENCE']
    
    SOUTH_CAROLINA = ['CLEMSON', 'PENDLETON']
    
    SOUTH_DAKOTA = ['PIERRE', 'RAPID CITY']
    
    TENNESSEE = ['BRISTOL', 'KINGSPORT', 'KNOXVILLE', 'MEMPHIS', 'NASHVILLE', 'OAK RIDGE']
    
    TEXAS = ['AUSTIN', 'BEAUMONT', 'COLLEGE STATION', 'DALLAS', 'DENTON', 'EL PASO', 'FORT WORTH', 'HOUSTON', 'LAREDO', 'LUBBOCK', 'SAN ANTONIO', 'WICHITA FALLS']
    
    UTAH = ['OGDEN', 'ROY', 'SALT LAKE CITY']
    
    VERMONT = ['BENNINGTON', 'MONTPELIER']
    
    VIRGINIA = ['ALEXANDRIA', 'BLACKSBURG', 'CHARLOTTESVILLE', 'NORFOLK', 'RICHMOND']
    
    WASHINGTON = ['OLYMPIA', 'SEATTLE']
    
    WEST_VIRGINIA = ['CHARLESTON', 'MORGANTOWN', 'WEIRTON']
    
    WISCONSIN = ['BENTON', 'KENOSHA', 'MADISON', 'MILWAUKEE', 'RHINELANDER', 'SHEBOYGAN', 'STEVENS POINT', 'SUPERIOR']
    
    WYOMING = ['CHEYENNE', 'ROCK SPRINGS']

class KANADA:
    ALBERTA = ['BANFF', 'CALGARY', 'EDMONTON', 'JASPER']
    
    BRITISH_COLOMBIA = ['ABBOTSFORD', 'BURNABY', 'COQUITLAM', 'KAMLOOPS', 'LOUISE ADASI', 'NANAIMO', 'RICHMOND', 'SAANICH', 'SURREY', 'VANCOUVER', 'VICTORIA']
    
    MANITOBA = ['WINNIPEG']
    
    NAL = ['HEBRON']
    
    NEW_BRUNSWICK = ['FREDERICTON', 'MONCTON', 'SAINT JOHN']
    
    NOVA_SCOTIA = ['HALIFAX', 'SYDNEY']
    
    NUNAVUT = ['IQALUIT']
    
    ONTORIO = ['BARRIE', 'BRAMPTON', 'BURLINGTON', 'CAMBRIDGE', 'CHATHAM', 'GUELPH', 'HAMILTON', 'KINGSTON', 'KITCHENER', 'LONDON', 'MARKHAM', 'MISSISSAUGA', 'OAKVILLE', 'OSHAWA', 'OTTAVA', 'OWEN SOUND', 'RICHMOND HILL', 'ST. CATHARINES', 'SUDBURY', 'THUNDER BAY', 'TORONTO', 'VAUGHAN', 'WINDSOR']
    
    PEI = ['CHARLOTTETOWN']
    
    QUEBECK = ['GATINEAU', 'HARRISON ISLAND', 'LAVAL', 'LONGUEUIL', 'MONTREAL', 'QUEBECK', 'RIMOUSKI', 'SEPT-ILES', 'SHERBROOKE']
    
    SASKATCHEWAN = ['REGINA']
    
class TURKIYE:
    ADANA = ['ADANA', 'ALADAG', 'CEYHAN', 'FEKE', 'KARAISALI', 'KARATAS', 'KOZAN', 'POZANTI', 'SAIMBEYLI', 'TUFANBEYLI', 'YUMURTALIK']

    ADIYAMAN = ['ADIYAMAN']
    
    AFYON = ['AFYON']
    
    AGRI = ['AGRI']
    
    AKSARAY = ['AKSARAY']
    
    AMASYA = ['AMASYA']
    
    ANKARA = ['AKYURT', 'ANKARA', 'AYAS', 'BALA', 'BEYPAZARI', 'CAMLIDERE', 'CUBUK', 'ELMADAG', 'EVREN', 'GUDUL', 'HAYMANA', 'KALECIK', 'KAZAN', 'KIZILCAHAMAM', 'NALLIHAN', 'POLATLI', 'SEREFLIKOCHISAR']
    
    ANTALYA = ['AKSEKI', 'AKSU', 'ALANYA', 'ANTALYA', 'DEMRE', 'ELMALI', 'FINIKE', 'GAZIPASA', 'GUNDOGMUS', 'IBRADI', 'KAS', 'KEMER', 'KORKUTELI', 'KUMLUCA', 'MANAVGAT', 'SERIK']
    
    ARDAHAN = ['ARDAHAN']
    
    ARTVIN = ['ARTVIN']
    
    AYDIN = ['AYDIN']
    
    BALIKESIR = ['BALIKESIR']
    
    BARTIN = ['BARTIN']
    
    BATMAN = ['BATMAN']
    
    BAYBURT = ['BAYBURT']
    
    BILECIK = ['BILECIK', 'BOZUYUK', 'GOLPAZARI', 'INHISAR', 'YENIPAZAR']
    
    BINGOL = ['BINGOL']
    
    BITLIS = ['BITLIS']
    
    BOLU = ['BOLU']
    
    BURDUR = ['BURDUR']
    
    BURSA = ['BURSA', 'BUYUK ORHAN', 'GEMLIK', 'HARMANCIK', 'INEGOL', 'IZNIK', 'KARACABEY', 'KELES', 'MUDANYA', 'MUSTAFA KEMALPASA', 'ORHANGAZI']
    
    CANAKKALE = ['CANAKKALE']
    
    CANKIRI = ['CANKIRI']
    
    CORUM = ['CORUM']
    
    DENIZLI = ['DENIZLI']
    
    DIYARBAKIR = ['BISMIL', 'CERMIK', 'CUNGUS', 'DICLE', 'DIYARBAKIR', 'EGIL', 'ERGANI', 'HANI', 'HAZRO', 'KOCAKOY', 'KULP', 'LICE', 'SILVAN']
    
    DUZCE = ['AKCAKOCA', 'DUZCE', 'GOLYAKA', 'KAYNASLI', 'YIGILCA']
    
    EDIRNE = ['EDIRNE']
    
    ELAZIG = ['ELAZIG']
    
    ERZINCAN = ['ERZINCAN']
    
    ERZURUM = ['ASKALE', 'AZIZIYE', 'CAT', 'ERZURUM', 'HINIS', 'HORASAN', 'ISPIR', 'KARACOBAN', 'KARAYAZI', 'KOPRUKOY', 'NARMAN', 'OLTU', 'OLUR', 'PASINLER', 'PAZARYOLU', 'SENKAYA', 'TEKMAN', 'TORTUM', 'UZUNDERE']
    
    ESKISEHIR = ['ESKISEHIR']
    
    GAZIANTEP = ['GAZIANTEP']
    
    GIRESUN = ['GIRESUN']
    
    GUMUSHANE = ['GUMUSHANE']
    
    HAKKARI = ['HAKKARI']
    
    HATAY = ['HATAY']
    
    IGDIR = ['IGDIR']
    
    ISPARTA = ['ISPARTA']
    
    ISTANBUL = ['ARNAVUTKOY', 'BEYLIKDUZU', 'BUYUKCEKMECE', 'CATALCA', 'CEKMEKOY', 'ESENYURT', 'ISTANBUL', 'KARTAL', 'KUCUKCEKMECE', 'MALTEPE', 'PENDIK', 'SANCAKTEPE', 'SILE', 'SILIVRI', 'SULTANBEYLI', 'SULTANGAZI', 'TUZLA']
    
    IZMIR = ['ALIAGA', 'BAYINDIR', 'BERGAMA', 'BEYDAG', 'CESME', 'DIKILI', 'FOCA', 'GUZELBAHCE', 'IZMIR', 'KARABURUN', 'KEMALPASA', 'KINIK', 'KIRAZ', 'ODEMIS', 'SEFERIHISAR', 'SELCUK', 'TIRE', 'TORBALI', 'URLA']
    
    KAHRAMANMARAS = ['KAHRAMANMARAS']
    
    KARABUK = ['KARABUK']
    
    KARAMAN = ['KARAMAN']
    
    KARS = ['KARS']
    
    KASTAMONU = ['KASTAMONU']
    
    KAYSERI = ['AKKISLA', 'BUNYAN', 'DEVELI', 'FELAHIYE', 'INCESU', 'KAYSERI', 'PINARBASI', 'SARIOGLAN', 'SARIZ', 'YAHYALI', 'YESILHISAR']
    
    KILIS = ['KILIS']
    
    KIRIKKALE = ['CELEBI', 'DELICE', 'KARAKECILI', 'KIRIKKALE', 'SULAKYURT']
    
    KIRKLARELI = ['KIRKLARELI']
    
    KIRSEHIR = ['AKPINAR', 'CICEKDAGI', 'KAMAN', 'KIRSEHIR', 'MUCUR']
    
    KOCAELI = ['CAYIROVA', 'DARICA', 'DILOVASI', 'GEBZE', 'KANDIRA', 'KARAMURSEL', 'KOCAELI']
    
    KONYA = ['AKOREN', 'AKSEHIR', 'ALTINEKIN', 'BEYSEHIR', 'BOZKIR', 'CIHANBEYLI', 'CUMRA', 'DERBENT', 'EREGLI', 'GUNEYSINIR', 'HADIM', 'HUYUK', 'ILGIN', 'KADINHANI', 'KARAPINAR', 'KONYA', 'KULU', 'SEYDISEHIR', 'YUNAK']
    
    KUTAHYA = ['KUTAHYA']
    
    MALATYA = ['MALATYA']
    
    MANISA = ['MANISA']
    
    MARDIN = ['DARGECIT', 'DERIK', 'KIZILTEPE', 'MARDIN', 'MAZIDAGI', 'MIDYAT', 'NUSAYBIN']
    
    MERSIN = ['ANAMUR', 'AYDINCIK', 'CAMLIYAYLA', 'ERDEMLI', 'GULNAR', 'MERSIN', 'MUT', 'SILIFKE', 'TARSUS']
    
    MUGLA = ['MUGLA']
    
    MUS = ['MUS']
    
    NEVSEHIR = ['NEVSEHIR']
    
    NIGDE = ['NIGDE']
    
    ORDU = ['ORDU']
    
    OSMANIYE = ['OSMANIYE']
    
    RIZE = ['ARDESEN', 'CAMLIHEMSIN', 'CAYELI', 'FINDIKLI', 'HEMSIN', 'IKIZDERE', 'IYIDERE', 'PAZAR', 'RIZE']
    
    SAKARYA = ['AKYAZI', 'GEYVE', 'HENDEK', 'KARASU', 'KAYNARCA', 'KOCAALI', 'PAMUKOVA', 'SAKARYA', 'TARAKLI']
    
    SAMSUN = ['SAMSUN']
    
    SANLIURFA = ['SANLIURFA']
    
    SIIRT = ['SIIRT']
    
    SINOP = ['SINOP']
    
    SIRNAK = ['SIRNAK']
    
    SIVAS = ['SIVAS']
    
    TEKIRDAG = ['TEKIRDAG']
    
    TOKAT = ['TOKAT']
    
    TRABZON = ['ARAKLI', 'ARSIN', 'CAYKARA', 'DERNEKPAZARI', 'DUZKOY', 'HAYRAT', 'OF', 'SURMENE', 'TONYA', 'TRABZON', 'VAKFIKEBIR']
    
    TUNCELI = ['TUNCELI']
    
    USAK = ['USAK']
    
    VAN = ['VAN']
    
    YALOVA = ['ALTINOVA', 'ARMUTLU', 'CINARCIK', 'TERMAL', 'YALOVA']
    
    YOZGAT = ['YOZGAT']
    
    ZONGULDAK = ['ZONGULDAK']