# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui, phonon
import PyVakitci_rc

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 511)
        MainWindow.setMinimumSize(QtCore.QSize(351, 511))
        MainWindow.setMaximumSize(QtCore.QSize(351, 511))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resimler/cami.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 330, 441))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(310, 441))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setIconSize(QtCore.QSize(38, 38))
        self.tabWidget.setObjectName("tabWidget")
        self.pyvakitci_tab = QtGui.QWidget()
        self.pyvakitci_tab.setObjectName("pyvakitci_tab")
        self.bilgiler_groupBox = QtGui.QGroupBox(self.pyvakitci_tab)
        self.bilgiler_groupBox.setEnabled(True)
        self.bilgiler_groupBox.setGeometry(QtCore.QRect(13, 12, 301, 64))
        self.bilgiler_groupBox.setMinimumSize(QtCore.QSize(280, 64))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.bilgiler_groupBox.setFont(font)
        self.bilgiler_groupBox.setTitle("")
        self.bilgiler_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bilgiler_groupBox.setFlat(False)
        self.bilgiler_groupBox.setCheckable(False)
        self.bilgiler_groupBox.setChecked(False)
        self.bilgiler_groupBox.setObjectName("bilgiler_groupBox")
        self.ulke_label = QtGui.QLabel(self.bilgiler_groupBox)
        self.ulke_label.setGeometry(QtCore.QRect(10, 10, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ulke_label.setFont(font)
        self.ulke_label.setObjectName("ulke_label")
        self.sehir_label = QtGui.QLabel(self.bilgiler_groupBox)
        self.sehir_label.setGeometry(QtCore.QRect(10, 40, 160, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.sehir_label.setFont(font)
        self.sehir_label.setObjectName("sehir_label")
        self.miladi_tarih = QtGui.QLabel(self.bilgiler_groupBox)
        self.miladi_tarih.setGeometry(QtCore.QRect(198, 10, 98, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.miladi_tarih.setFont(font)
        self.miladi_tarih.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.miladi_tarih.setObjectName("miladi_tarih")
        self.hicri_tarih = QtGui.QLabel(self.bilgiler_groupBox)
        self.hicri_tarih.setGeometry(QtCore.QRect(156, 25, 140, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hicri_tarih.setFont(font)
        self.hicri_tarih.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hicri_tarih.setObjectName("hicri_tarih")
        self.saat_label = QtGui.QLabel(self.bilgiler_groupBox)
        self.saat_label.setGeometry(QtCore.QRect(204, 40, 92, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.saat_label.setFont(font)
        self.saat_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.saat_label.setObjectName("saat_label")
        self.namaz_vakitleri_groupBox = QtGui.QGroupBox(self.pyvakitci_tab)
        self.namaz_vakitleri_groupBox.setGeometry(QtCore.QRect(13, 84, 301, 301))
        self.namaz_vakitleri_groupBox.setMinimumSize(QtCore.QSize(280, 281))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setWeight(50)
        font.setBold(False)
        self.namaz_vakitleri_groupBox.setFont(font)
        self.namaz_vakitleri_groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.namaz_vakitleri_groupBox.setTitle("")
        self.namaz_vakitleri_groupBox.setObjectName("namaz_vakitleri_groupBox")
        self.namaz_vakti_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.namaz_vakti_label.setGeometry(QtCore.QRect(88, 15, 145, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.namaz_vakti_label.setFont(font)
        self.namaz_vakti_label.setObjectName("namaz_vakti_label")
        self.line = QtGui.QFrame(self.namaz_vakitleri_groupBox)
        self.line.setGeometry(QtCore.QRect(40, 30, 221, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(221, 16))
        self.line.setMaximumSize(QtCore.QSize(221, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.imsak_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.imsak_label.setGeometry(QtCore.QRect(92, 55, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.imsak_label.setFont(font)
        self.imsak_label.setObjectName("imsak_label")
        self.gunes_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.gunes_label.setGeometry(QtCore.QRect(92, 85, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.gunes_label.setFont(font)
        self.gunes_label.setObjectName("gunes_label")
        self.ogle_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.ogle_label.setGeometry(QtCore.QRect(92, 115, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.ogle_label.setFont(font)
        self.ogle_label.setObjectName("ogle_label")
        self.ikindi_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.ikindi_label.setGeometry(QtCore.QRect(92, 145, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.ikindi_label.setFont(font)
        self.ikindi_label.setObjectName("ikindi_label")
        self.aksam_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.aksam_label.setGeometry(QtCore.QRect(92, 175, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.aksam_label.setFont(font)
        self.aksam_label.setObjectName("aksam_label")
        self.yatsi_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.yatsi_label.setGeometry(QtCore.QRect(92, 205, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.yatsi_label.setFont(font)
        self.yatsi_label.setObjectName("yatsi_label")
        self.nokta_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label.setGeometry(QtCore.QRect(152, 57, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.nokta_label.setFont(font)
        self.nokta_label.setObjectName("nokta_label")
        self.nokta_label_2 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_2.setGeometry(QtCore.QRect(152, 87, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.nokta_label_2.setFont(font)
        self.nokta_label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.nokta_label_2.setObjectName("nokta_label_2")
        self.nokta_label_3 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_3.setGeometry(QtCore.QRect(152, 117, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.nokta_label_3.setFont(font)
        self.nokta_label_3.setObjectName("nokta_label_3")
        self.nokta_label_4 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_4.setGeometry(QtCore.QRect(152, 147, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.nokta_label_4.setFont(font)
        self.nokta_label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.nokta_label_4.setObjectName("nokta_label_4")
        self.nokta_label_5 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_5.setGeometry(QtCore.QRect(152, 177, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.nokta_label_5.setFont(font)
        self.nokta_label_5.setObjectName("nokta_label_5")
        self.nokta_label_6 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_6.setGeometry(QtCore.QRect(152, 207, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.nokta_label_6.setFont(font)
        self.nokta_label_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.nokta_label_6.setObjectName("nokta_label_6")
        self.imsak_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.imsak_saat_label.setGeometry(QtCore.QRect(172, 58, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.imsak_saat_label.setFont(font)
        self.imsak_saat_label.setObjectName("imsak_saat_label")
        self.gunes_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.gunes_saat_label.setGeometry(QtCore.QRect(172, 88, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.gunes_saat_label.setFont(font)
        self.gunes_saat_label.setObjectName("gunes_saat_label")
        self.ogle_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.ogle_saat_label.setGeometry(QtCore.QRect(172, 118, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.ogle_saat_label.setFont(font)
        self.ogle_saat_label.setObjectName("ogle_saat_label")
        self.ikindi_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.ikindi_saat_label.setGeometry(QtCore.QRect(172, 148, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.ikindi_saat_label.setFont(font)
        self.ikindi_saat_label.setObjectName("ikindi_saat_label")
        self.aksam_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.aksam_saat_label.setGeometry(QtCore.QRect(172, 178, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.aksam_saat_label.setFont(font)
        self.aksam_saat_label.setObjectName("aksam_saat_label")
        self.yatsi_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.yatsi_saat_label.setGeometry(QtCore.QRect(172, 208, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.yatsi_saat_label.setFont(font)
        self.yatsi_saat_label.setObjectName("yatsi_saat_label")
        self.sonraki_vakit_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.sonraki_vakit_label.setGeometry(QtCore.QRect(95, 235, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.sonraki_vakit_label.setFont(font)
        self.sonraki_vakit_label.setObjectName("sonraki_vakit_label")
        self.kalan_sure_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.kalan_sure_label.setGeometry(QtCore.QRect(120, 255, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.kalan_sure_label.setFont(font)
        self.kalan_sure_label.setObjectName("kalan_sure_label")
        self.tabWidget.addTab(self.pyvakitci_tab, icon, "")
        self.bolgesel_ayarlar_tab = QtGui.QWidget()
        self.bolgesel_ayarlar_tab.setObjectName("bolgesel_ayarlar_tab")
        self.bolgesel_ayarlar_groupBox = QtGui.QGroupBox(self.bolgesel_ayarlar_tab)
        self.bolgesel_ayarlar_groupBox.setGeometry(QtCore.QRect(13, 4, 301, 381))
        self.bolgesel_ayarlar_groupBox.setMinimumSize(QtCore.QSize(280, 381))
        self.bolgesel_ayarlar_groupBox.setObjectName("bolgesel_ayarlar_groupBox")
        self.bolgesel_ayarlar_ulke_label = QtGui.QLabel(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_ulke_label.setGeometry(QtCore.QRect(15, 31, 71, 17))
        self.bolgesel_ayarlar_ulke_label.setObjectName("bolgesel_ayarlar_ulke_label")
        self.ulkeler_comboBox = QtGui.QComboBox(self.bolgesel_ayarlar_groupBox)
        self.ulkeler_comboBox.setGeometry(QtCore.QRect(80, 26, 200, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ulkeler_comboBox.sizePolicy().hasHeightForWidth())
        self.ulkeler_comboBox.setSizePolicy(sizePolicy)
        self.ulkeler_comboBox.setEditable(False)
        self.ulkeler_comboBox.setDuplicatesEnabled(False)
        self.ulkeler_comboBox.setObjectName("ulkeler_comboBox")
        self.bolgesel_ayarlar_sehir_label = QtGui.QLabel(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_sehir_label.setGeometry(QtCore.QRect(15, 71, 71, 17))
        self.bolgesel_ayarlar_sehir_label.setObjectName("bolgesel_ayarlar_sehir_label")
        self.sehirler_comboBox = QtGui.QComboBox(self.bolgesel_ayarlar_groupBox)
        self.sehirler_comboBox.setGeometry(QtCore.QRect(80, 66, 200, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sehirler_comboBox.sizePolicy().hasHeightForWidth())
        self.sehirler_comboBox.setSizePolicy(sizePolicy)
        self.sehirler_comboBox.setEditable(False)
        self.sehirler_comboBox.setObjectName("sehirler_comboBox")
        self.bolgesel_ayarlar_kaydet_pushButton = QtGui.QPushButton(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_kaydet_pushButton.setGeometry(QtCore.QRect(200, 345, 85, 28))
        self.bolgesel_ayarlar_kaydet_pushButton.setObjectName("bolgesel_ayarlar_kaydet_pushButton")
        self.kaynak_comboBox = QtGui.QComboBox(self.bolgesel_ayarlar_groupBox)
        self.kaynak_comboBox.setGeometry(QtCore.QRect(80, 146, 200, 27))
        self.kaynak_comboBox.setObjectName("kaynak_comboBox")
        self.kaynak_comboBox.addItem("")
        self.kaynak_comboBox.addItem("")
        self.kaynak_label = QtGui.QLabel(self.bolgesel_ayarlar_groupBox)
        self.kaynak_label.setGeometry(QtCore.QRect(15, 151, 71, 17))
        self.kaynak_label.setObjectName("kaynak_label")
        self.bolgesel_ayarlar_varsayilan_pushButton = QtGui.QPushButton(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_varsayilan_pushButton.setGeometry(QtCore.QRect(110, 345, 85, 28))
        self.bolgesel_ayarlar_varsayilan_pushButton.setObjectName("bolgesel_ayarlar_varsayilan_pushButton")
        self.ilceler_comboBox = QtGui.QComboBox(self.bolgesel_ayarlar_groupBox)
        self.ilceler_comboBox.setEnabled(False)
        self.ilceler_comboBox.setGeometry(QtCore.QRect(80, 106, 200, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ilceler_comboBox.sizePolicy().hasHeightForWidth())
        self.ilceler_comboBox.setSizePolicy(sizePolicy)
        self.ilceler_comboBox.setEditable(False)
        self.ilceler_comboBox.setObjectName("ilceler_comboBox")
        self.bolgesel_ayarlar_ilce_label = QtGui.QLabel(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_ilce_label.setGeometry(QtCore.QRect(15, 111, 71, 17))
        self.bolgesel_ayarlar_ilce_label.setObjectName("bolgesel_ayarlar_ilce_label")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resimler/world.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.bolgesel_ayarlar_tab, icon1, "")
        self.ayarlar_tab = QtGui.QWidget()
        self.ayarlar_tab.setObjectName("ayarlar_tab")
        self.ayarlar_groupBox = QtGui.QGroupBox(self.ayarlar_tab)
        self.ayarlar_groupBox.setGeometry(QtCore.QRect(13, 4, 301, 381))
        self.ayarlar_groupBox.setMinimumSize(QtCore.QSize(280, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ayarlar_groupBox.setFont(font)
        self.ayarlar_groupBox.setFlat(False)
        self.ayarlar_groupBox.setObjectName("ayarlar_groupBox")
        self.otomatik_calistir_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.otomatik_calistir_checkBox.setGeometry(QtCore.QRect(10, 25, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otomatik_calistir_checkBox.sizePolicy().hasHeightForWidth())
        self.otomatik_calistir_checkBox.setSizePolicy(sizePolicy)
        self.otomatik_calistir_checkBox.setObjectName("otomatik_calistir_checkBox")
        self.her_zaman_ustte_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.her_zaman_ustte_checkBox.setGeometry(QtCore.QRect(10, 100, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.her_zaman_ustte_checkBox.sizePolicy().hasHeightForWidth())
        self.her_zaman_ustte_checkBox.setSizePolicy(sizePolicy)
        self.her_zaman_ustte_checkBox.setObjectName("her_zaman_ustte_checkBox")
        self.ezan_oku_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.ezan_oku_checkBox.setGeometry(QtCore.QRect(10, 150, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ezan_oku_checkBox.sizePolicy().hasHeightForWidth())
        self.ezan_oku_checkBox.setSizePolicy(sizePolicy)
        self.ezan_oku_checkBox.setObjectName("ezan_oku_checkBox")
        self.dua_oku_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.dua_oku_checkBox.setEnabled(False)
        self.dua_oku_checkBox.setGeometry(QtCore.QRect(10, 175, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dua_oku_checkBox.sizePolicy().hasHeightForWidth())
        self.dua_oku_checkBox.setSizePolicy(sizePolicy)
        self.dua_oku_checkBox.setObjectName("dua_oku_checkBox")
        self.erken_uyari_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.erken_uyari_checkBox.setGeometry(QtCore.QRect(10, 200, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.erken_uyari_checkBox.sizePolicy().hasHeightForWidth())
        self.erken_uyari_checkBox.setSizePolicy(sizePolicy)
        self.erken_uyari_checkBox.setObjectName("erken_uyari_checkBox")
        self.erken_uyari_lineEdit = QtGui.QLineEdit(self.ayarlar_groupBox)
        self.erken_uyari_lineEdit.setEnabled(True)
        self.erken_uyari_lineEdit.setGeometry(QtCore.QRect(250, 201, 25, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.erken_uyari_lineEdit.sizePolicy().hasHeightForWidth())
        self.erken_uyari_lineEdit.setSizePolicy(sizePolicy)
        self.erken_uyari_lineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.erken_uyari_lineEdit.setMaxLength(2)
        self.erken_uyari_lineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.erken_uyari_lineEdit.setObjectName("erken_uyari_lineEdit")
        self.uyari_sesi_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.uyari_sesi_checkBox.setEnabled(False)
        self.uyari_sesi_checkBox.setGeometry(QtCore.QRect(10, 225, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uyari_sesi_checkBox.sizePolicy().hasHeightForWidth())
        self.uyari_sesi_checkBox.setSizePolicy(sizePolicy)
        self.uyari_sesi_checkBox.setObjectName("uyari_sesi_checkBox")
        self.ayarlar_kaydet_pushButton = QtGui.QPushButton(self.ayarlar_groupBox)
        self.ayarlar_kaydet_pushButton.setGeometry(QtCore.QRect(200, 345, 85, 28))
        self.ayarlar_kaydet_pushButton.setObjectName("ayarlar_kaydet_pushButton")
        self.ayarlar_varsayilan_pushButton = QtGui.QPushButton(self.ayarlar_groupBox)
        self.ayarlar_varsayilan_pushButton.setGeometry(QtCore.QRect(110, 345, 85, 28))
        self.ayarlar_varsayilan_pushButton.setObjectName("ayarlar_varsayilan_pushButton")
        self.besmele_ile_basla_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.besmele_ile_basla_checkBox.setGeometry(QtCore.QRect(10, 125, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.besmele_ile_basla_checkBox.sizePolicy().hasHeightForWidth())
        self.besmele_ile_basla_checkBox.setSizePolicy(sizePolicy)
        self.besmele_ile_basla_checkBox.setObjectName("besmele_ile_basla_checkBox")
        self.otomatik_guncellestir_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.otomatik_guncellestir_checkBox.setGeometry(QtCore.QRect(10, 75, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otomatik_guncellestir_checkBox.sizePolicy().hasHeightForWidth())
        self.otomatik_guncellestir_checkBox.setSizePolicy(sizePolicy)
        self.otomatik_guncellestir_checkBox.setObjectName("otomatik_guncellestir_checkBox")
        self.sistem_tepsisinde_baslat_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.sistem_tepsisinde_baslat_checkBox.setGeometry(QtCore.QRect(10, 50, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sistem_tepsisinde_baslat_checkBox.sizePolicy().hasHeightForWidth())
        self.sistem_tepsisinde_baslat_checkBox.setSizePolicy(sizePolicy)
        self.sistem_tepsisinde_baslat_checkBox.setObjectName("sistem_tepsisinde_baslat_checkBox")
        self.vakitleri_goster_pushButton = QtGui.QPushButton(self.ayarlar_groupBox)
        self.vakitleri_goster_pushButton.setGeometry(QtCore.QRect(32, 275, 250, 26))
        self.vakitleri_goster_pushButton.setObjectName("vakitleri_goster_pushButton")
        self.vakitleri_aylik_al_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.vakitleri_aylik_al_checkBox.setGeometry(QtCore.QRect(10, 250, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vakitleri_aylik_al_checkBox.sizePolicy().hasHeightForWidth())
        self.vakitleri_aylik_al_checkBox.setSizePolicy(sizePolicy)
        self.vakitleri_aylik_al_checkBox.setObjectName("vakitleri_aylik_al_checkBox")
        self.vakitleri_guncelle_pushButton = QtGui.QPushButton(self.ayarlar_groupBox)
        self.vakitleri_guncelle_pushButton.setGeometry(QtCore.QRect(32, 310, 250, 26))
        self.vakitleri_guncelle_pushButton.setObjectName("vakitleri_guncelle_pushButton")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resimler/ayarlar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.ayarlar_tab, icon2, "")
        self.ses_dosyalari_tab = QtGui.QWidget()
        self.ses_dosyalari_tab.setObjectName("ses_dosyalari_tab")
        self.sabah_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.sabah_ses_label.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.sabah_ses_label.setObjectName("sabah_ses_label")
        self.sabah_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.sabah_lineEdit.setGeometry(QtCore.QRect(80, 17, 190, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sabah_lineEdit.sizePolicy().hasHeightForWidth())
        self.sabah_lineEdit.setSizePolicy(sizePolicy)
        self.sabah_lineEdit.setReadOnly(True)
        self.sabah_lineEdit.setObjectName("sabah_lineEdit")
        self.sabah_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.sabah_toolButton.setGeometry(QtCore.QRect(280, 18, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sabah_toolButton.sizePolicy().hasHeightForWidth())
        self.sabah_toolButton.setSizePolicy(sizePolicy)
        self.sabah_toolButton.setObjectName("sabah_toolButton")
        self.dua_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.dua_toolButton.setGeometry(QtCore.QRect(280, 208, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dua_toolButton.sizePolicy().hasHeightForWidth())
        self.dua_toolButton.setSizePolicy(sizePolicy)
        self.dua_toolButton.setObjectName("dua_toolButton")
        self.dua_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.dua_ses_label.setGeometry(QtCore.QRect(10, 210, 70, 17))
        self.dua_ses_label.setObjectName("dua_ses_label")
        self.aksam_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.aksam_ses_label.setGeometry(QtCore.QRect(10, 134, 70, 17))
        self.aksam_ses_label.setObjectName("aksam_ses_label")
        self.aksam_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.aksam_lineEdit.setGeometry(QtCore.QRect(80, 131, 190, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aksam_lineEdit.sizePolicy().hasHeightForWidth())
        self.aksam_lineEdit.setSizePolicy(sizePolicy)
        self.aksam_lineEdit.setReadOnly(True)
        self.aksam_lineEdit.setObjectName("aksam_lineEdit")
        self.aksam_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.aksam_toolButton.setGeometry(QtCore.QRect(280, 132, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aksam_toolButton.sizePolicy().hasHeightForWidth())
        self.aksam_toolButton.setSizePolicy(sizePolicy)
        self.aksam_toolButton.setObjectName("aksam_toolButton")
        self.uyari_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.uyari_toolButton.setGeometry(QtCore.QRect(280, 246, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uyari_toolButton.sizePolicy().hasHeightForWidth())
        self.uyari_toolButton.setSizePolicy(sizePolicy)
        self.uyari_toolButton.setObjectName("uyari_toolButton")
        self.yatsi_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.yatsi_ses_label.setGeometry(QtCore.QRect(10, 172, 70, 17))
        self.yatsi_ses_label.setObjectName("yatsi_ses_label")
        self.yatsi_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.yatsi_lineEdit.setGeometry(QtCore.QRect(80, 169, 190, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yatsi_lineEdit.sizePolicy().hasHeightForWidth())
        self.yatsi_lineEdit.setSizePolicy(sizePolicy)
        self.yatsi_lineEdit.setReadOnly(True)
        self.yatsi_lineEdit.setObjectName("yatsi_lineEdit")
        self.yatsi_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.yatsi_toolButton.setGeometry(QtCore.QRect(280, 170, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yatsi_toolButton.sizePolicy().hasHeightForWidth())
        self.yatsi_toolButton.setSizePolicy(sizePolicy)
        self.yatsi_toolButton.setObjectName("yatsi_toolButton")
        self.uyari_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.uyari_ses_label.setGeometry(QtCore.QRect(10, 248, 70, 17))
        self.uyari_ses_label.setObjectName("uyari_ses_label")
        self.ogle_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.ogle_ses_label.setGeometry(QtCore.QRect(10, 58, 70, 17))
        self.ogle_ses_label.setObjectName("ogle_ses_label")
        self.ogle_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.ogle_lineEdit.setGeometry(QtCore.QRect(80, 55, 190, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ogle_lineEdit.sizePolicy().hasHeightForWidth())
        self.ogle_lineEdit.setSizePolicy(sizePolicy)
        self.ogle_lineEdit.setReadOnly(True)
        self.ogle_lineEdit.setObjectName("ogle_lineEdit")
        self.ogle_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.ogle_toolButton.setGeometry(QtCore.QRect(280, 56, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ogle_toolButton.sizePolicy().hasHeightForWidth())
        self.ogle_toolButton.setSizePolicy(sizePolicy)
        self.ogle_toolButton.setObjectName("ogle_toolButton")
        self.uyari_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.uyari_lineEdit.setGeometry(QtCore.QRect(80, 245, 190, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uyari_lineEdit.sizePolicy().hasHeightForWidth())
        self.uyari_lineEdit.setSizePolicy(sizePolicy)
        self.uyari_lineEdit.setReadOnly(True)
        self.uyari_lineEdit.setObjectName("uyari_lineEdit")
        self.dua_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.dua_lineEdit.setGeometry(QtCore.QRect(80, 207, 190, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dua_lineEdit.sizePolicy().hasHeightForWidth())
        self.dua_lineEdit.setSizePolicy(sizePolicy)
        self.dua_lineEdit.setReadOnly(True)
        self.dua_lineEdit.setObjectName("dua_lineEdit")
        self.ikindi_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.ikindi_ses_label.setGeometry(QtCore.QRect(10, 96, 70, 17))
        self.ikindi_ses_label.setObjectName("ikindi_ses_label")
        self.ikindi_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.ikindi_lineEdit.setGeometry(QtCore.QRect(80, 93, 190, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ikindi_lineEdit.sizePolicy().hasHeightForWidth())
        self.ikindi_lineEdit.setSizePolicy(sizePolicy)
        self.ikindi_lineEdit.setReadOnly(True)
        self.ikindi_lineEdit.setObjectName("ikindi_lineEdit")
        self.ikindi_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.ikindi_toolButton.setGeometry(QtCore.QRect(280, 97, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ikindi_toolButton.sizePolicy().hasHeightForWidth())
        self.ikindi_toolButton.setSizePolicy(sizePolicy)
        self.ikindi_toolButton.setObjectName("ikindi_toolButton")
        self.ses_kaydet_pushButton = QtGui.QPushButton(self.ses_dosyalari_tab)
        self.ses_kaydet_pushButton.setGeometry(QtCore.QRect(230, 335, 85, 28))
        self.ses_kaydet_pushButton.setObjectName("ses_kaydet_pushButton")
        self.ses_varsayilan_pushButton = QtGui.QPushButton(self.ses_dosyalari_tab)
        self.ses_varsayilan_pushButton.setGeometry(QtCore.QRect(140, 335, 85, 28))
        self.ses_varsayilan_pushButton.setObjectName("ses_varsayilan_pushButton")
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.ses_dosyalari_tab)
        self.volumeSlider.setGeometry(QtCore.QRect(200, 290, 117, 30))
        self.volumeSlider.setObjectName("volumeSlider")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resimler/ses_dosyalari.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.ses_dosyalari_tab, icon3, "")
        self.linkler_tab = QtGui.QWidget()
        self.linkler_tab.setObjectName("linkler_tab")
        self.linkler_groupBox = QtGui.QGroupBox(self.linkler_tab)
        self.linkler_groupBox.setGeometry(QtCore.QRect(13, 4, 301, 381))
        self.linkler_groupBox.setObjectName("linkler_groupBox")
        self.site_01_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_01_label.setGeometry(QtCore.QRect(15, 20, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_01_label.sizePolicy().hasHeightForWidth())
        self.site_01_label.setSizePolicy(sizePolicy)
        self.site_01_label.setObjectName("site_01_label")
        self.site_02_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_02_label.setGeometry(QtCore.QRect(15, 50, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_02_label.sizePolicy().hasHeightForWidth())
        self.site_02_label.setSizePolicy(sizePolicy)
        self.site_02_label.setObjectName("site_02_label")
        self.site_03_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_03_label.setGeometry(QtCore.QRect(15, 80, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_03_label.sizePolicy().hasHeightForWidth())
        self.site_03_label.setSizePolicy(sizePolicy)
        self.site_03_label.setObjectName("site_03_label")
        self.site_05_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_05_label.setGeometry(QtCore.QRect(15, 140, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_05_label.sizePolicy().hasHeightForWidth())
        self.site_05_label.setSizePolicy(sizePolicy)
        self.site_05_label.setObjectName("site_05_label")
        self.site_06_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_06_label.setGeometry(QtCore.QRect(15, 170, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_06_label.sizePolicy().hasHeightForWidth())
        self.site_06_label.setSizePolicy(sizePolicy)
        self.site_06_label.setObjectName("site_06_label")
        self.site_07_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_07_label.setGeometry(QtCore.QRect(15, 200, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_07_label.sizePolicy().hasHeightForWidth())
        self.site_07_label.setSizePolicy(sizePolicy)
        self.site_07_label.setObjectName("site_07_label")
        self.site_08_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_08_label.setGeometry(QtCore.QRect(15, 230, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_08_label.sizePolicy().hasHeightForWidth())
        self.site_08_label.setSizePolicy(sizePolicy)
        self.site_08_label.setObjectName("site_08_label")
        self.site_09_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_09_label.setGeometry(QtCore.QRect(15, 260, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_09_label.sizePolicy().hasHeightForWidth())
        self.site_09_label.setSizePolicy(sizePolicy)
        self.site_09_label.setObjectName("site_09_label")
        self.site_10_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_10_label.setGeometry(QtCore.QRect(15, 290, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_10_label.sizePolicy().hasHeightForWidth())
        self.site_10_label.setSizePolicy(sizePolicy)
        self.site_10_label.setObjectName("site_10_label")
        self.site_11_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_11_label.setGeometry(QtCore.QRect(15, 320, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_11_label.sizePolicy().hasHeightForWidth())
        self.site_11_label.setSizePolicy(sizePolicy)
        self.site_11_label.setObjectName("site_11_label")
        self.site_12_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_12_label.setGeometry(QtCore.QRect(15, 350, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_12_label.sizePolicy().hasHeightForWidth())
        self.site_12_label.setSizePolicy(sizePolicy)
        self.site_12_label.setObjectName("site_12_label")
        self.site_04_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_04_label.setGeometry(QtCore.QRect(15, 110, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_04_label.sizePolicy().hasHeightForWidth())
        self.site_04_label.setSizePolicy(sizePolicy)
        self.site_04_label.setObjectName("site_04_label")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resimler/linkler.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.linkler_tab, icon4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 351, 26))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.menuDosya.setFont(font)
        self.menuDosya.setObjectName("menuDosya")
        self.menuYardim = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.menuYardim.setFont(font)
        self.menuYardim.setObjectName("menuYardim")
        self.menuGorunum = QtGui.QMenu(self.menubar)
        self.menuGorunum.setObjectName("menuGorunum")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLisans = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionLisans.setFont(font)
        self.actionLisans.setObjectName("actionLisans")
        self.actionHakkinda = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionHakkinda.setFont(font)
        self.actionHakkinda.setObjectName("actionHakkinda")
        self.actionQtHakkinda = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionQtHakkinda.setFont(font)
        self.actionQtHakkinda.setObjectName("actionQtHakkinda")
        self.actionCikis = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resimler/cikis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCikis.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionCikis.setFont(font)
        self.actionCikis.setIconVisibleInMenu(True)
        self.actionCikis.setObjectName("actionCikis")
        self.actionCleanlooks = QtGui.QAction(MainWindow)
        self.actionCleanlooks.setObjectName("actionCleanlooks")
        self.actionPlastique = QtGui.QAction(MainWindow)
        self.actionPlastique.setObjectName("actionPlastique")
        self.actionWindowsXP = QtGui.QAction(MainWindow)
        self.actionWindowsXP.setObjectName("actionWindowsXP")
        self.actionWindowsVista = QtGui.QAction(MainWindow)
        self.actionWindowsVista.setObjectName("actionWindowsVista")
        self.actionOxygen = QtGui.QAction(MainWindow)
        self.actionOxygen.setObjectName("actionOxygen")
        self.menuDosya.addAction(self.actionCikis)
        self.menuYardim.addAction(self.actionLisans)
        self.menuYardim.addSeparator()
        self.menuYardim.addAction(self.actionHakkinda)
        self.menuYardim.addAction(self.actionQtHakkinda)
        self.menuGorunum.addAction(self.actionCleanlooks)
        self.menuGorunum.addAction(self.actionOxygen)
        self.menuGorunum.addAction(self.actionPlastique)
        self.menuGorunum.addAction(self.actionWindowsXP)
        self.menuGorunum.addAction(self.actionWindowsVista)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuGorunum.menuAction())
        self.menubar.addAction(self.menuYardim.menuAction())

        self.actionVakitleriGoster = QtGui.QAction(MainWindow)
        self.actionVakitleriGoster.setIcon(icon)
        self.actionVakitleriGoster.setFont(font)
        self.actionVakitleriGoster.setIconVisibleInMenu(True)
        self.actionVakitleriGoster.setObjectName("actionVakitleriGoster")
        
        self.trayIcon = QtGui.QSystemTrayIcon(self)
        menu = QtGui.QMenu(self)
        menu.addAction(self.actionVakitleriGoster)
        menu.addAction(self.actionCikis)
        self.trayIcon.setContextMenu(menu)
        self.trayIcon.setIcon(QtGui.QIcon(":resimler/cami.png"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.ulkeler_comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyVakitci", None, QtGui.QApplication.UnicodeUTF8))
        self.ulke_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.sehir_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.miladi_tarih.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.hicri_tarih.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.saat_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.namaz_vakti_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.imsak_label.setText(QtGui.QApplication.translate("MainWindow", "İmsak", None, QtGui.QApplication.UnicodeUTF8))
        self.gunes_label.setText(QtGui.QApplication.translate("MainWindow", "Güneş", None, QtGui.QApplication.UnicodeUTF8))
        self.ogle_label.setText(QtGui.QApplication.translate("MainWindow", "Öğle", None, QtGui.QApplication.UnicodeUTF8))
        self.ikindi_label.setText(QtGui.QApplication.translate("MainWindow", "İkindi", None, QtGui.QApplication.UnicodeUTF8))
        self.aksam_label.setText(QtGui.QApplication.translate("MainWindow", "Akşam", None, QtGui.QApplication.UnicodeUTF8))
        self.yatsi_label.setText(QtGui.QApplication.translate("MainWindow", "Yatsı", None, QtGui.QApplication.UnicodeUTF8))
        self.nokta_label.setText(QtGui.QApplication.translate("MainWindow", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.nokta_label_2.setText(QtGui.QApplication.translate("MainWindow", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.nokta_label_3.setText(QtGui.QApplication.translate("MainWindow", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.nokta_label_4.setText(QtGui.QApplication.translate("MainWindow", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.nokta_label_5.setText(QtGui.QApplication.translate("MainWindow", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.nokta_label_6.setText(QtGui.QApplication.translate("MainWindow", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.imsak_saat_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.gunes_saat_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ogle_saat_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ikindi_saat_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.aksam_saat_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.yatsi_saat_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.sonraki_vakit_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.kalan_sure_label.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pyvakitci_tab), "")
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.pyvakitci_tab), QtGui.QApplication.translate("MainWindow", "Namaz Vakitleri", None, QtGui.QApplication.UnicodeUTF8))
        self.bolgesel_ayarlar_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Bölgesel Ayarlar", None, QtGui.QApplication.UnicodeUTF8))
        self.bolgesel_ayarlar_ulke_label.setText(QtGui.QApplication.translate("MainWindow", "Ülke :", None, QtGui.QApplication.UnicodeUTF8))
        self.bolgesel_ayarlar_sehir_label.setText(QtGui.QApplication.translate("MainWindow", "Şehir :", None, QtGui.QApplication.UnicodeUTF8))
        self.bolgesel_ayarlar_kaydet_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Program kapanıp açıldığında yaptığınız değişikliklerin\n"
"hatırlanması için buraya tıklayın.", None, QtGui.QApplication.UnicodeUTF8))
        self.bolgesel_ayarlar_kaydet_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Kaydet", None, QtGui.QApplication.UnicodeUTF8))
        self.kaynak_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "diyanet.gov.tr", None, QtGui.QApplication.UnicodeUTF8))
        self.kaynak_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "zaman.com.tr", None, QtGui.QApplication.UnicodeUTF8))
        self.kaynak_label.setText(QtGui.QApplication.translate("MainWindow", "Kaynak :", None, QtGui.QApplication.UnicodeUTF8))
        self.bolgesel_ayarlar_varsayilan_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Varsayılan ayarlara dönmek isterseniz buraya tıklayın.", None, QtGui.QApplication.UnicodeUTF8))
        self.bolgesel_ayarlar_varsayilan_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Varsayılan", None, QtGui.QApplication.UnicodeUTF8))
        self.bolgesel_ayarlar_ilce_label.setText(QtGui.QApplication.translate("MainWindow", "İlçe :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bolgesel_ayarlar_tab), "")
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.bolgesel_ayarlar_tab), QtGui.QApplication.translate("MainWindow", "Bölgesel Ayarlar", None, QtGui.QApplication.UnicodeUTF8))
        self.ayarlar_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Ayarlar", None, QtGui.QApplication.UnicodeUTF8))
        self.otomatik_calistir_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Açılışta programı otomatik çalıştır.", None, QtGui.QApplication.UnicodeUTF8))
        self.her_zaman_ustte_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Her zaman üstte göster.", None, QtGui.QApplication.UnicodeUTF8))
        self.ezan_oku_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Vakit girdiğinde ezan oku.", None, QtGui.QApplication.UnicodeUTF8))
        self.dua_oku_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Ezandan sonra ezan duasını oku.", None, QtGui.QApplication.UnicodeUTF8))
        self.erken_uyari_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Vakit girmeden önce uyar (dk.):", None, QtGui.QApplication.UnicodeUTF8))
        self.erken_uyari_lineEdit.setInputMask(QtGui.QApplication.translate("MainWindow", "99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.erken_uyari_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.uyari_sesi_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Uyarı sesi çal.", None, QtGui.QApplication.UnicodeUTF8))
        self.ayarlar_kaydet_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Program kapanıp açıldığında yaptığınız değişikliklerin\n"
"hatırlanması için buraya tıklayın.", None, QtGui.QApplication.UnicodeUTF8))
        self.ayarlar_kaydet_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Kaydet", None, QtGui.QApplication.UnicodeUTF8))
        self.ayarlar_varsayilan_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Varsayılan ayarlara dönmek isterseniz buraya tıklayın.", None, QtGui.QApplication.UnicodeUTF8))
        self.ayarlar_varsayilan_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Varsayılan", None, QtGui.QApplication.UnicodeUTF8))
        self.besmele_ile_basla_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Besmele ile başla.", None, QtGui.QApplication.UnicodeUTF8))
        self.otomatik_guncellestir_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Güncellemeleri kontrol et.", None, QtGui.QApplication.UnicodeUTF8))
        self.sistem_tepsisinde_baslat_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Programı sistem tepsisinde başlat.", None, QtGui.QApplication.UnicodeUTF8))
        self.vakitleri_goster_pushButton.setText(QtGui.QApplication.translate("MainWindow", " Vakitleri aylık olarak göster.", None, QtGui.QApplication.UnicodeUTF8))
        self.vakitleri_aylik_al_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Vakitleri aylık olarak al.", None, QtGui.QApplication.UnicodeUTF8))
        self.vakitleri_guncelle_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Aylık vakitleri şimdi güncelle.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ayarlar_tab), "")
        self.sabah_ses_label.setText(QtGui.QApplication.translate("MainWindow", "Sabah :", None, QtGui.QApplication.UnicodeUTF8))
        self.sabah_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Ekle", None, QtGui.QApplication.UnicodeUTF8))
        self.dua_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Ekle", None, QtGui.QApplication.UnicodeUTF8))
        self.dua_ses_label.setText(QtGui.QApplication.translate("MainWindow", "Dua :", None, QtGui.QApplication.UnicodeUTF8))
        self.aksam_ses_label.setText(QtGui.QApplication.translate("MainWindow", "Akşam :", None, QtGui.QApplication.UnicodeUTF8))
        self.aksam_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Ekle", None, QtGui.QApplication.UnicodeUTF8))
        self.uyari_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Ekle", None, QtGui.QApplication.UnicodeUTF8))
        self.yatsi_ses_label.setText(QtGui.QApplication.translate("MainWindow", "Yatsı :", None, QtGui.QApplication.UnicodeUTF8))
        self.yatsi_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Ekle", None, QtGui.QApplication.UnicodeUTF8))
        self.uyari_ses_label.setText(QtGui.QApplication.translate("MainWindow", "Uyarı :", None, QtGui.QApplication.UnicodeUTF8))
        self.ogle_ses_label.setText(QtGui.QApplication.translate("MainWindow", "Öğle :", None, QtGui.QApplication.UnicodeUTF8))
        self.ogle_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Ekle", None, QtGui.QApplication.UnicodeUTF8))
        self.ikindi_ses_label.setText(QtGui.QApplication.translate("MainWindow", "İkindi :", None, QtGui.QApplication.UnicodeUTF8))
        self.ikindi_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Ekle", None, QtGui.QApplication.UnicodeUTF8))
        self.ses_kaydet_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Program kapanıp açıldığında yaptığınız değişikliklerin\n"
"hatırlanması için buraya tıklayın.", None, QtGui.QApplication.UnicodeUTF8))
        self.ses_kaydet_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Kaydet", None, QtGui.QApplication.UnicodeUTF8))
        self.ses_varsayilan_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Varsayılan ayarlara dönmek isterseniz buraya tıklayın.", None, QtGui.QApplication.UnicodeUTF8))
        self.ses_varsayilan_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Varsayılan", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ses_dosyalari_tab), "")
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.ses_dosyalari_tab), QtGui.QApplication.translate("MainWindow", "Ses Dosyaları", None, QtGui.QApplication.UnicodeUTF8))
        self.linkler_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Yararlı Siteler", None, QtGui.QApplication.UnicodeUTF8))
        self.site_01_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.sorularlaislamiyet.com/\">Sorularla İslamiyet</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_02_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.namazladirilis.com/sbahnamazi.htm\">Namaz ve Önemi</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_03_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.dinimizislam.com/detay.asp?id=4318\">Kur\'an-ı Kerim Öğreniyorum</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_05_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.diyanet.gov.tr/turkish/ihtida/sureler/index.html\">Diyanet Seçme Sûreler</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_06_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.diyanet.gov.tr/kuran/default.asp\">Diyanet (Kur\'an-ı Kerim ve Meâli)</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_07_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://tanzil.info/\">Tanzil (Kur\'an-ı Kerim ve Meâli)</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_08_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.hadis.gen.tr/\">Hadis.gen.tr</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_09_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.enfal.de/hadis.htm\">Hadis Sayfası</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_10_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.e-hadis.com/\">Hadis Arama Motoru</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_11_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.diyanet.gov.tr/turkish/dy/Diyanet-Isleri-Baskanligi-AnaMenu-dini-gunler-ve-geceler-182.aspx\">Dini Günler ve Geceler</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_12_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://www.erisale.com/\">Risale-i Nur Külliyatı</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.site_04_label.setText(QtGui.QApplication.translate("MainWindow", "<a href=\"http://kuran.tv/\">Kuran.tv</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linkler_tab), "")
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.linkler_tab), QtGui.QApplication.translate("MainWindow", "Yararlı Siteler", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDosya.setTitle(QtGui.QApplication.translate("MainWindow", "Dosya", None, QtGui.QApplication.UnicodeUTF8))
        self.menuYardim.setTitle(QtGui.QApplication.translate("MainWindow", "Yardım", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGorunum.setTitle(QtGui.QApplication.translate("MainWindow", "Görünüm", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLisans.setText(QtGui.QApplication.translate("MainWindow", "Lisans", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHakkinda.setText(QtGui.QApplication.translate("MainWindow", "Hakkında", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQtHakkinda.setText(QtGui.QApplication.translate("MainWindow", "Qt Hakkında", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCikis.setText(QtGui.QApplication.translate("MainWindow", "Çıkış", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCikis.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCleanlooks.setText(QtGui.QApplication.translate("MainWindow", "Cleanlooks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlastique.setText(QtGui.QApplication.translate("MainWindow", "Plastique", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVakitleriGoster.setText(QtGui.QApplication.translate("MainWindow", "Vakitleri Göster", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWindowsXP.setText(QtGui.QApplication.translate("MainWindow", "Windows XP", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWindowsVista.setText(QtGui.QApplication.translate("MainWindow", "Windows Vista", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOxygen.setText(QtGui.QApplication.translate("MainWindow", "Oxygen", None, QtGui.QApplication.UnicodeUTF8))

